# Generated by Django 4.2.11 on 2024-07-21 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='listing',
            field=models.ForeignKey(default=21, on_delete=django.db.models.deletion.CASCADE, to='market.listing'),
            preserve_default=False,
        ),
    ]
