# Generated by Django 4.2.11 on 2024-07-22 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_alter_bid_listing_alter_comment_listing_watchlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='listings/'),
        ),
    ]
