# Generated by Django 4.2.11 on 2024-07-23 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_alter_listing_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='level',
            field=models.CharField(default=2, max_length=4),
            preserve_default=False,
        ),
    ]
